
LASEROIDE_ACCELERATION = 0.8#1 = 1 fois world.ratio
LASEROIDE_RAD = 50
LASEROIDE_ATK_RAD = 30
LASEROIDE_TOO_CLOSE = 10

DEFENDEUR_ACCELERATION = 0.9#1 = 1 fois world.ratio
DEFENDEUR_RAD = 30
DEFENDEUR_ATK_RAD = 15
DEFENDEUR_TOO_CLOSE = -1 #So never

FOULLI_ATTAQUE_RAD = 5