
LASEROIDE_ACCELERATION = 0.8#1 = 1 fois world.ratio
LASEROIDE_RAD = 50
LASEROIDE_ATK_RAD = 30
LASEROIDE_TOO_CLOSE = 10

DEFENDEUR_ACCELERATION = 0.9#1 = 1 fois world.ratio
DEFENDEUR_RAD = 30
DEFENDEUR_ATK_RAD = 15
DEFENDEUR_TOO_CLOSE = -1 #So never

ESCARGOT_ACCELERATION = 0.5#1 = 1 fois world.ratio
ESCARGOT_RAD = 300
ESCARGOT_ATK_RAD = -1
ESCARGOT_TOO_CLOSE = -1 #So never

LIMACE_ACCELERATION = 0.4 #1 = 1 fois world.ratio
LIMACE_RAD = 300
LIMACE_ATK_RAD = 20
LIMACE_TOO_CLOSE = -1 #So never

FOULLI_ATTAQUE_RAD = 5