from shared.constants.world import RATIO

LIFE_FIRE = 4
V_FIRE = 200 * RATIO #Bouge de 20 cellules par secondes
WIDTH_FIRE = 2*RATIO
HEIGHT_FIRE = 2*RATIO
REBOND_FIRE = False
DAMAGE_FIRE = 5
WEIGHT_FIRE = 255

LIFE_MAGIC = 4
V_MAGIC = 200 * RATIO #Bouge de 20 cellules par secondes
WIDTH_MAGIC = 2*RATIO
HEIGHT_MAGIC = 2*RATIO
REBOND_MAGIC = False
DAMAGE_MAGIC = 5
WEIGHT_MAGIC = 255

REFILL_TIME_WEAPON1 = 1
SPELL_TIME_WEAPON1 = 0.1
NBR_SLOT_WEAPON1 = 3
NBR_UPGRADES_TRIGGER_WEAPON1 = 1
ID_WEAPON1 = 0