from shared.constants.world import RATIO

LIFE_FIREBALL = 2
V_FIREBALL = 200 * RATIO #Bouge de 20 cellules par secondes
WIDTH_FIREBALL = 2*RATIO
HEIGHT_FIREBALL = 2*RATIO
REBOND_FIREBALL = True

REFILL_TIME_WEAPON1 = 1
SPELL_TIME_WEAPON1 = 0.2
NBR_SLOT_WEAPON1 = 3
NBR_UPGRADES_TRIGGER_WEAPON1 = 1
ID_WEAPON1 = 0