nbr_cell_see_y = 64
CELL_SIZE = 16

PLAYER_SIZE_HEIGHT = 8
PLAYER_SIZE_WIDTH = 8

TOMBE_SIZE_HEIGHT = 8
TOMBE_SIZE_WIDTH = 6

CHEST_SIZE_HEIGHT = 8
CHEST_SIZE_WITH = 8

SIZE_SPELL_GROUND = 4
DELTA_SIZE_BG_SPELL = 1