PROJECTILE_0_HEIGHT = 3
PROJECTILE_0_WIDTH = 12

PROJECTILE_2_HEIGHT = 1
PROJECTILE_2_WIDTH = 1

PROJECTILE_3_HEIGHT = 5
PROJECTILE_3_WIDTH = 5

PROJECTILE_4_HEIGHT = 2
PROJECTILE_4_WIDTH = 2

PROJECTILE_5_HEIGHT = 2
PROJECTILE_5_WIDTH = 2

PROJECTILE_7_HEIGHT = 1
PROJECTILE_7_WIDTH = 1

PROJECTILE_8_HEIGHT = 3
PROJECTILE_8_WIDTH = 10