PROJECTILE_0_HEIGHT = 3
PROJECTILE_0_WIDTH = 12

PROJECTILE_2_HEIGHT = 2
PROJECTILE_2_WIDTH = 2

PROJECTILE_3_HEIGHT = 5
PROJECTILE_3_WIDTH = 5

PROJECTILE_4_HEIGHT = 2
PROJECTILE_4_WIDTH = 2

PROJECTILE_5_HEIGHT = 2
PROJECTILE_5_WIDTH = 2

PROJECTILE_7_HEIGHT = 3
PROJECTILE_7_WIDTH = 3

PROJECTILE_8_HEIGHT = 3
PROJECTILE_8_WIDTH = 10

PROJECTILE_9_HEIGHT = 3
PROJECTILE_9_WIDTH = 3

PROJECTILE_44_HEIGHT = 4
PROJECTILE_44_WIDTH = 4

PROJECTILE_45_HEIGHT = 4
PROJECTILE_45_WIDTH = 4

PROJECTILE_48_HEIGHT = 6
PROJECTILE_48_WIDTH = 6